services:
  app:
    container_name: carnet-app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["php-fpm"]
    restart: unless-stopped
    env_file: .env
    user: www-data
    working_dir: /var/www
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
      - carnet-app-public:/var/www/public
      - .env:/var/www/.env
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - carnet-network

  web:
    image: nginx:stable-alpine
    container_name: carnet-nginx
    restart: always
    ports:
      - "9010:80" # Port public (host:container)
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - carnet-app-public:/var/www/public
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - carnet-network

  db:
    image: postgres:15
    container_name: carnet-postgres
    restart: always
    ports:
      - "5435:5432" # Port PostgreSQL exposé
    environment:
      POSTGRES_DB: recettes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: samwin25
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carnet-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  carnet-app-public:

networks:
  carnet-network:
    external: true
    name: carnet-network
